/**
 * Fetch the web fonts into the repository so the app stops loading them
 * from Google.
 *
 * The page used to pull Inter and JetBrains Mono from fonts.googleapis.com.
 * While this was a tool you ran locally that was a detail. Published, it
 * meant the IP address and user agent of every visitor reached a third
 * party before a single pixel rendered, in an application whose stated
 * claim is that nothing leaves the browser. Self-hosting is the only way
 * that claim survives contact with a public page.
 *
 *   node scripts/fetch-fonts.mjs
 *
 * Writes woff2 files to src/assets/fonts/ and regenerates src/fonts.css.
 * Both are committed: a build should not depend on Google being reachable.
 *
 * Only Latin, Latin Extended and Greek, and only the weights the interface
 * uses.
 *
 * Google answers with variable fonts: one file per family and subset that
 * carries every weight. Asking for four weights returns the same bytes four
 * times over. This script notices and stores the file once, so the four
 * @font-face rules point at a single download instead of at four identical
 * copies of it.
 */

import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = join(ROOT, 'src', 'assets', 'fonts');

// Chrome, so the API answers with woff2 rather than an older format.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

// 300 is deliberately absent: nothing in the interface uses font-light.
const CSS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=Inter:wght@400;500;600;700' +
  '&family=JetBrains+Mono:wght@400;500;600' +
  '&display=swap';

const SUBSETS = new Set(['latin', 'latin-ext', 'greek']);

const LICENCES = {
  'inter-OFL.txt': 'https://raw.githubusercontent.com/rsms/inter/master/LICENSE.txt',
  'jetbrains-mono-OFL.txt':
    'https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/OFL.txt'
};

const HEADER = `/* Fonts served with the app, not fetched from a third party.
 *
 * These used to load from fonts.googleapis.com. On a tool you ran locally
 * that was a detail; on a published page it meant every visitor's IP and
 * user agent reached Google before anything rendered, in an application
 * whose whole claim is that nothing leaves the browser.
 *
 * Inter and JetBrains Mono are both under the SIL Open Font License, which
 * permits redistribution. Licence texts are in src/assets/fonts/.
 *
 * Generated by scripts/fetch-fonts.mjs. Do not edit by hand.
 */

`;

async function get(url) {
  const response = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!response.ok) throw new Error(`HTTP ${response.status} for ${url}`);
  return response;
}

async function main() {
  mkdirSync(FONT_DIR, { recursive: true });

  const css = await (await get(CSS_URL)).text();
  const blocks = [...css.matchAll(/\/\* (\S+) \*\/\s*(@font-face \{[\s\S]*?\})/g)];
  if (blocks.length === 0) throw new Error('no @font-face blocks in the response');

  const rules = [];
  const byContent = new Map();
  let downloaded = 0;

  for (const [, subset, block] of blocks) {
    if (!SUBSETS.has(subset)) continue;

    const family = /font-family: '([^']+)'/.exec(block)[1];
    const weight = /font-weight: (\d+)/.exec(block)[1];
    const url = /url\((https:\/\/[^)]+)\)/.exec(block)[1];
    const range = /unicode-range: ([^;]+);/.exec(block)[1];

    const bytes = Buffer.from(await (await get(url)).arrayBuffer());
    const digest = createHash('sha256').update(bytes).digest('hex');

    // The same variable font arrives once per weight. Keep one copy.
    let file = byContent.get(digest);
    if (!file) {
      file = `${family.toLowerCase().replace(/ /g, '-')}-${subset}.woff2`;
      writeFileSync(join(FONT_DIR, file), bytes);
      byContent.set(digest, file);
      downloaded += 1;
    }

    rules.push(
      `@font-face {\n` +
        `  font-family: '${family}';\n` +
        `  font-style: normal;\n` +
        `  font-weight: ${weight};\n` +
        // swap, so text is readable in the fallback face while the real one
        // loads rather than the page showing nothing.
        `  font-display: swap;\n` +
        `  src: url('./assets/fonts/${file}') format('woff2');\n` +
        `  unicode-range: ${range};\n` +
        `}`
    );
  }

  writeFileSync(join(ROOT, 'src', 'fonts.css'), HEADER + rules.join('\n\n') + '\n');

  for (const [name, url] of Object.entries(LICENCES)) {
    writeFileSync(join(FONT_DIR, name), await (await get(url)).text());
  }

  console.log(
    `Wrote ${rules.length} @font-face rules over ${downloaded} files, ` +
      `and ${Object.keys(LICENCES).length} licences`
  );
}

main().catch((error) => {
  console.error(`Could not fetch the fonts: ${error.message}`);
  process.exit(1);
});
